### PR TITLE
Add setting level

### PR DESCRIPTION
**Pull request by GivemeHam**
Add setLevel() function to set level in tetris.c.
SetLevel control game->sleepUsec value in initGame().

### CODE REVIEW

**Comment by ecelctus** [comment]
i think line79 should change to " int select_level = 0; " for initialize variables before using them. Other than that, it seems good.

**Comment by GivemeHam** [comment]
@ecelctus  Good Comment!

**Comment by Ssook** [comment]
If i write a number in 1~5, after writing unexpected number like 7,8,100,a .. ,
this code does not work.

**Comment by GivemeHam** [comment]
@Ssook Ok. I checked it. I will edit the codes as quickly..

**Comment by ecelctus** [comment]
I checked Update initialize line79 in tetris.c (4eaf421)

thanks for consider opinion.

**Comment by Ssook** [comment]
I checked it.(cf8fecd)

**Pull request merged**
